blockchain.blockchain_node.*:
  type: config_entity
  label: 'Blockchain Node config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    self:
      type: string
      label: 'ID'
    address:
      type: string
      label: 'Node host/ip'
    ip:
      type: string
      label: 'Node ip'
    port:
      type: string
      label: 'Node port'
    secure:
      type: boolean
      label: 'Is protocol secure'
    blockchainTypeId:
      type: string
      label: 'Related blockchain type id'
    addressSource:
      type: string
      label: 'Source of address'
