blockchain.blockchain_config.*:
  type: config_entity
  label: 'Blockchain config config'
  mapping:
    id:
      type: string
      label: 'ID supposed to be same as block entity type'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    blockchainId:
      type: string
      label: 'Blockchain identifier'
    nodeId:
      type: string
      label: 'Blockchain node identifier'
    type:
      type: string
      label: 'Type of blockchain'
    auth:
      type: string
      label: 'Use auth token or not'
    filterType:
      type: string
      label: 'Type of blockchain nodes filtering'
    filterList:
      type: string
      label: 'List of blockchain nodes IPs to filter'
    poolManagement:
      type: string
      label: 'Type of pool management'
    announceManagement:
      type: string
      label: 'Type of announce management'
    intervalPool:
      type: integer
      label: 'Interval for CRON blockchain pool management'
    timeoutPool:
      type: integer
      label: 'Timeout for CRON blockchain pool management'
    intervalAnnounce:
      type: integer
      label: 'Interval for CRON syncing with other blockchain nodes'
    pullSizeAnnounce:
      type: integer
      label: 'Pull size for announce handling'
    searchIntervalAnnounce:
      type: integer
      label: 'Search interval for announce handling'
    powPosition:
      type: string
      label: 'Proof of work position'
    powExpression:
      type: string
      label: 'Proof of work expression'
    dataHandler:
      type: string
      label: 'Data handler for blockchain'
    allowNotSecure:
      type: boolean
      label: 'Allows not secure blockchain nodes'
