blockchain.blockchain_node.*:
  type: config_entity
  label: 'Blockchain Node config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    ip:
      type: string
      label: 'Node ip'
    port:
      type: string
      label: 'Node port'
    secure:
      type: boolean
      label: 'Is protocol secure'