blockchain.config:
  type: config_object
  label: 'Blockchain config'
  mapping:
    blockchainType:
      type: string
      label: 'Type of blockchain'
    blockchainId:
      type: string
      label: 'Blockchain identifier'
    blockchainNodeId:
      type: string
      label: 'Blockchain node identifier'
    poolManagement:
      type: string
      label: 'Type of pool management'
    announceManagement:
      type: string
      label: 'Type of announce management'
    intervalPool:
      type: integer
      label: 'Interval for CRON blockchain pool management'
    intervalAnnounce:
      type: integer
      label: 'Interval for CRON syncing with other blockchain nodes'
    powPosition:
      type: string
      label: 'Proof of work position'
    powExpression:
      type: string
      label: 'Proof of work expression'
    dataHandler:
      type: string
      label: 'Data handler for blockchain'