blockchain.config:
  type: config_object
  label: 'Blockchain config'
  mapping:
    type:
      type: string
      label: 'Type of blockchain'
    id:
      type: string
      label: 'Blockchain identifier'
    pool_management:
      type: string
      label: 'Type of pool management'
    announce_management:
      type: string
      label: 'Type of announce management'
    interval_pool:
      type: integer
      label: 'Interval for CRON blockchain pool management'
    interval_announce:
      type: integer
      label: 'Interval for CRON syncing with other blockchain nodes'
    pof_position:
      type: string
      label: 'Proof of work position'
    pof_expression:
      type: string
      label: 'Proof of work expression'