blockchain.config:
  type: config_object
  label: 'Blockchain config'
  mapping:
    type:
      type: string
      label: 'Type of blockchain'
    pool_management:
      type: string
      label: 'Type of pool management'
    announce_management:
      type: string
      label: 'Type of announce management'
    interval:
      type: integer
      label: 'Interval for syncing with other blockchain nodes'
